name: build

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PRIVATE_REPO: ${{ secrets.PRIVATE_REPO }}

permissions:
  contents: write

on:
  repository_dispatch:
    types: [pubspec-updated]
  workflow_dispatch:

jobs:
  check-for-version:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.get-info.outputs.name }}
      version: ${{ steps.get-info.outputs.version }}
      pkg: ${{ steps.get-info.outputs.pkg }}
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v5
        with:
          repository: ${{ env.PRIVATE_REPO }}
          token: ${{ secrets.ORG_TOKEN }}

      - name: Get name and version from pubspec.yaml
        id: get-info
        run: |
          NAME=$(grep '^name:' pubspec.yaml | sed 's/name: *//' | tr -d ' ')
          PKG=$(grep 'applicationId' android/app/build.gradle.kts | sed 's/.*applicationId = "\(.*\)".*/\1/')
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: *//' | tr -d ' ')
          echo "name=${NAME}" >> $GITHUB_OUTPUT
          echo "pkg=${PKG}" >> $GITHUB_OUTPUT
          echo "version=v${VERSION}" >> $GITHUB_OUTPUT
          echo "Detected name: ${NAME}"
          echo "Detected package: ${PKG}"
          echo "Detected version: v${VERSION}"

  # build-windows:
  #   needs: check-for-version
  #   uses: ./.github/workflows/build-windows.yml
  #   with:
  #     name: ${{ needs.check-for-version.outputs.name }}
  #     pkg: ${{ needs.check-for-version.outputs.pkg }}
  #     version: ${{ needs.check-for-version.outputs.version }}
  #   secrets: inherit

  build-android:
    needs: check-for-version
    uses: ./.github/workflows/build-android.yml
    with:
      name: ${{ needs.check-for-version.outputs.name }}
      pkg: ${{ needs.check-for-version.outputs.pkg }}
      version: ${{ needs.check-for-version.outputs.version }}
    secrets: inherit

  # build-apple:
  #   needs: check-for-version
  #   uses: ./.github/workflows/build-apple.yml
  #   with:
  #     name: ${{ needs.check-for-version.outputs.name }}
  #     pkg: ${{ needs.check-for-version.outputs.pkg }}
  #     version: ${{ needs.check-for-version.outputs.version }}
  #   secrets: inherit
